### ISSUE TITLE
Bug: Publishr config is all wrong + not used on latest publication.

### ISSUE THREAD

**Issue by jchip** [FormidableLabs/component-playground#118]
Latest package.json has these dependencies:
```
  "dependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^6.4.1",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "babel-standalone": "^6.26.0",
    "codemirror": "^5.30.0",
    "prop-types": "^15.6.0",
    "react": "^16.0.0",
    "react-codemirror2": "^2.0.2",
    "react-dom": "^16.0.0",
    "rimraf": "^2.6.2",
    "webpack": "^1.15.0"
  },
```
- Of the `babel-*` packages, under `src` I only see `babel-standalone` used.
- I don't see `webpack` used under `src`

Are these extra packages that are typically dev only need somewhere that I missed?

**Comment by jchip** [comment]
I see that publishr is suppose to take care of this, but the latest version 3.0.0 published still have these dev dep in `dependencies`.  Maybe publishr is not working as intended?  @ryan-roemer

**Comment by ryan-roemer** [comment]
@jchip -- Yeah, something's not right. I'll try republishing over the top of that and see if it's fixed.

**Comment by ryan-roemer** [comment]
Also https://github.com/FormidableLabs/component-playground/blob/master/.npmignore.publishr is wrong. 

Best course of action:

- [ ] Start off of https://github.com/FormidableLabs/component-playground/pull/115
- [ ] Make sure `es/` and `lib/` and `dist/` are published
- [ ] Add `prop-types` back as real dependency (per official docs).
- [ ] Remove everything else

**Comment by ryan-roemer** [comment]
@jchip --`component-playground@3.1.1` ( https://unpkg.com/component-playground@3.1.1/ ) looks good as far as I can tell. Kick the tires and let me know how it goes on your end. (Also, we added `es` transpiled output for `package.json:module` entry point which webpack should like in your modern builds...)

**Comment by jchip** [comment]
@ryan-roemer thanks.  the latest 3.1.1 dependencies from npm is now:

```
  "dependencies": {
    "babel-standalone": "^6.26.0",
    "codemirror": "^5.30.0",
    "prop-types": "^15.6.0",
    "react-codemirror2": "^2.0.2"
  },
  "peerDependencies": {
    "react": "^15.6.0 || ^16.0.0",
    "react-dom": "^15.6.0 || ^16.0.0"
  },
```
