### ISSUE TITLE
Backticks in docs

### ISSUE THREAD

**Issue by zslabs** [FormidableLabs/component-playground#120]
👋 

After upgrading from `3.0.0` to `3.1.1` I noticed that the generated docs are coming along with back-ticks. It looks like this came with https://github.com/FormidableLabs/component-playground/compare/v3.0.0...master#diff-6f3133d9d003ccbfc175f0de54f2c74c but I'm not sure I'm seeing any reason for it.

<img width="376" alt="screen shot 2018-01-30 at 10 24 23 am" src="https://user-images.githubusercontent.com/1018402/35574534-06e91874-05a8-11e8-87c3-4f871b84b4fa.png">

**Comment by kale-stew** [comment]
It looks like [this PR](https://github.com/FormidableLabs/component-playground/pull/112) is the source of this issue in the generated docs. I'm going to toy with it some more, but I think the next step is identifying what's going to parse down correctly in that `<b>` tag.

**Comment by kale-stew** [comment]
(I was wrong & this was never a parsing issue, simply a template literal syntax bug). 🙂

**Comment by zslabs** [comment]
Ah ok no worries! Thanks for looking into that.

**Comment by zslabs** [comment]
Any chance of a new release around this fix?

**Comment by ryan-roemer** [comment]
@zslabs -- Yikes! Sorry we missed the publish.

Released in `component-playground@3.1.2`
