### ISSUE TITLE
Differences between this and react-live

### ISSUE THREAD

**Issue by johncmunson** [FormidableLabs/component-playground#126]
The two projects seem to be accomplishing the exact same thing. Since they are both maintained by Formidable, I'm assuming there are some high level differences between the two?

https://github.com/FormidableLabs/react-live

**Comment by ryan-roemer** [comment]
Great question, and we've already written up itemized list of the differences so our end users can make an informed choice:

- https://github.com/FormidableLabs/react-live#comparison-to-component-playground
- https://github.com/FormidableLabs/component-playground#comparison-to-react-live

**Comment by johncmunson** [comment]
Wow, I jumped right into the issues to see if someone had already asked this question. Of course not, it was right in the readme :sweat_smile:
