### ISSUE TITLE
Missing dependency on babel-polyfill

### ISSUE THREAD

**Issue by nwalters512** [FormidableLabs/component-playground#132]
In v3.2.0, the latest, `es/components/playground.js` tries to import `babel-polyfill`. However, this is not declared in the published `package.json`, even though it's declared in the `package.json` in this repo. What's up with this?

**Comment by ryan-roemer** [comment]
We re-write `package.json` on publishing to support two scenarios:

- git dependencies: need full build dependencies to build after install via `postinstall`
- npm dependencies: don't need build deps nor `postinstall`

We do this via a tool https://github.com/FormidableLabs/publishr

I suspect we have an errant configuration of what to swap on publishing that will be a short fix.

**Comment by nwalters512** [comment]
Thanks so much for the quick fix!
