### ISSUE TITLE
Pre-Build JavaScript File Error

### ISSUE THREAD

**Issue by pburtchaell** [FormidableLabs/component-playground#14]
When I import the playground component, I get this error: 

```
WARNING in ./~/component-playground/~/babel-core/browser.js
Critical dependencies:
1:478-485 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/component-playground/~/babel-core/browser.js 1:478-485
```

I'm using WebPack + Babel to compile the demo.

**Comment by kenwheeler** [comment]
This originates from a bug in babel where if you require babel in a file that is processed by babel, using webpack, it throws. Babel's author recommended using browser.js, with this compilation warning being an unfortunate side-effect.
