### ISSUE TITLE
Show original example code in preview

### ISSUE THREAD

**Issue by tp** [FormidableLabs/component-playground#38]
Would it be possible to show the original ES6 Code in the CodeMirror editor instead of the transpiled version?

**Comment by alexlande** [comment]
This should work unless it was broken very recently. You can see an example here: http://projects.formidablelabs.com/es6-interactive-guide/

**Comment by tp** [comment]
Thanks I will compare that project to mine and hopefully get a clue why it is only showing the transpiled here.

**Comment by alexlande** [comment]
Going to close this one since there's no repro. Please leave a comment if you're still having trouble with it!
