### ISSUE TITLE
Uncaught Invariant Violation

### ISSUE THREAD

**Issue by svenadlung** [FormidableLabs/component-playground#57]
I don't get this running, please give me some guidance. I tried last release and v1.0.0. I did "npm install" and then "npm run dev". I always get following errors:

![localhost 3000 webpack-dev-server](https://cloud.githubusercontent.com/assets/11420688/13730611/f3d2afba-e953-11e5-9d6f-28c18bb4726e.png)

Did I miss sth?

**Comment by svenadlung** [comment]
Does anyone have an idea?

**Comment by kenwheeler** [comment]
Looking into this

**Comment by kenwheeler** [comment]
Fixed on master
