### ISSUE TITLE
Error trying to import

### ISSUE THREAD

**Issue by jrios** [FormidableLabs/component-playground#58]
I get a strange error when I am trying to import Component Playground in my JS files. Here's the error that I'm seeing in dev tools when I have `import Playground from 'component-playground'`:

![with-playground](https://cloud.githubusercontent.com/assets/520657/13937974/d56ea092-ef8e-11e5-8b2b-509126d9d4b8.PNG)

Here's a repo with a simple example of what I have that illustrates the problem. https://github.com/jrios/playground-webpack

Am I missing something?

**Comment by jrios** [comment]
Looking more at this issue, it could be related to this issue https://github.com/FormidableLabs/component-playground/issues/28

**Comment by kenwheeler** [comment]
not seeing playground in your deps, but i'm sure that isn't it. i'll pull your copy down and see what I can find

**Comment by jrios** [comment]
sorry about that. I added component-playground and react-dom to make sure all deps were met and in the configuration.

thanks for helping out with this!

**Comment by jrios** [comment]
I also just verified that this problem is also occurring for me regardless of whether or not I'm using babel-loader for webpack.

Node Version 4.3
npm version 2.14.12

dep list:

├── babel-core@6.7.2
├── babel-loader@6.2.4
├── babel-preset-es2015@6.6.0
├── babel-preset-react@6.5.0
├── component-playground@1.2.0
├── react@0.14.7
├── react-dom@0.14.7
└── webpack@1.12.14
