### ISSUE TITLE
Code Mirror dependency using npm

### ISSUE THREAD

**Issue by prakashsanker** [FormidableLabs/component-playground#60]
Instead of including code mirror using

```
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.0.0/codemirror.min.js"></script>
 <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.0.0/mode/javascript/javascript.min.js"></script>
```

Is there a way to use `component-playground` by npm installing code-mirror? Maybe using this component - https://github.com/JedWatson/react-codemirror

**Comment by NogsMPLS** [comment]
this is actualyl already in master branch via this PR: https://github.com/FormidableLabs/component-playground/pull/55

new version just hasn't been tagged yet.

**Comment by kylecesmat** [comment]
closed by https://github.com/FormidableLabs/component-playground/pull/55
