### ISSUE TITLE
Server rendering broken

### ISSUE THREAD

**Issue by alexlande** [FormidableLabs/component-playground#75]
I found today that `component-playground` can't be server rendered because of the code mirror dependency it's bundled with now. Code mirror is browser-only, so you get `navigator is not defined` when you try to server render.

The solution for me right now is to only load `component-playground` in the browser. We could fix the issue here by only loading code mirror in the browser, which I would like a little bit better, personally.

**Comment by RobTiu** [comment]
Hi Alexlande,

I'm currently having this issue right now.  I'm currently using the mern stack and it's complaining the navigator is not defined when I use component-playground.  Sorry but I'm still new to react and i wanted to know how you can load component-playground only in the browser?

**Comment by alexlande** [comment]
My fix for this was pretty quick and hacky. I'm using the `exenv` module (https://github.com/JedWatson/exenv) to check if I'm in the browser, and conditionally loading ComponentPlayground based on that. (So the webpack build that generates my client-side JS includes ComponentPlayground, but on the server it's not used.)

```js
// Only load ComponentPlayground in client, because it throws an error on the server.
// https://github.com/FormidableLabs/component-playground/issues/75
const ComponentPlayground = !exEnv.canUseDOM ? null : require('component-playground').default;
```

Then, I'm checking for the existence of `ComponentPlayground` when I render it:

```js
<div>
  { ComponentPlayground && (
    <ComponentPlayground />
  ) }
</div>
```

**Comment by alexlande** [comment]
Looking at this again, this will be a pretty easy fix now that component playground is using `react-codemirror`. We'll just need to only import the codemirror JSX mode if we're in the browser. I'll submit a PR to get this fixed for real.

**Comment by alexlande** [comment]
@RobTiu: try version 1.3.2, server rendering works again 👍

**Comment by RobTiu** [comment]
Thanks alexlande!  I'll give it a shot.
